duckdb_extension_load(core_functions)
duckdb_extension_load(parquet)
duckdb_extension_load(json)
duckdb_extension_load(icu)
include("/build/duckdb/.github/config/extensions/httpfs.cmake")
include("/build/duckdb/.github/config/extensions/aws.cmake")
